name: PHPUnit

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false

      matrix:
        php-versions: ['7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP, Composer and Extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: dom, mbstring, xdebug

      - name: Install dependencies
        run: composer update --optimize-autoloader --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run tests
        run: php vendor/bin/phpunit
